# Generated by Django 4.2.1 on 2023-06-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('quant', models.IntegerField()),
                ('disponivel', models.BooleanField()),
                ('dt_cadatro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
